DesktopResponsive={"1009":{
"pageLayer":{"w":1600,"h":900,"bgColor":"#ffffff"}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
}}
